import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@repo/ui/styles.css";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} relative bg-[#212121]`}>
        {children}
        <div
          className={"absolute top-0 h-screen w-screen overflow-hidden -z-10"}
        >
          <div
            style={{
              width: "100%",
              height: "100%",
              background:
                "url(noise.png), linear-gradient(180deg, rgba(239, 218, 218, 0.1) 0%, rgba(237, 237, 237, 0.1) 53.5%, rgba(135, 135, 135, 0.1) 100%)",
              backdropFilter: "blur(40px)",
              opacity: 0.5,
            }}
          ></div>
          <div
            style={{
              position: "absolute",
              zIndex: -20,
              width: 1100,
              height: 1100,
              left: "-40.44%",
              bottom: "-50.52%",
              background: "linear-gradient(180deg, #9F8383 0%, #706C8A 100%)",
              filter: "blur(450px)",
              borderRadius: "50%",
              transform: "matrix(-0.42, -0.91, 0.89, -0.45, 0, 0)",
            }}
          ></div>
          <div
            style={{
              position: "absolute",
              zIndex: -20,
              right: "9%",
              top: "30%",
              width: 295,
              height: 280,
              borderRadius: "50%",
              background: "linear-gradient(180deg, #D37373 30%, #2F14D7 100%)",
              filter: "blur(55.7px)",
              transform: "matrix(0.45, 0.89, -0.9, 0.43, 0, 0)",
            }}
          ></div>
          <div
            style={{
              position: "absolute",
              height: "30%",
              width: "30%",
              right: "-400px",
              bottom: "-260px",
              background: "linear-gradient(180deg, #9F8383 0%, #706C8A 100%)",
              filter: "blur(142.05px)",
              transform: "rotate(30deg)",
            }}
          ></div>
        </div>
      </body>
    </html>
  );
}
